apiVersion: v1
kind: Template
labels:
  template: rhdm78-kieserver-cors
  group: xpaas
metadata:
  name: rhdm78-kieserver-cors
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rhdm78-kieserver-cors
    annotations:
    labels:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: rhdm78-kieserver-cors
    annotations:
      description: Builds Red Hat Decision Manager KIE-Server image with CORS support.
    labels:
      name: rhdm78-kieserver-cors
      app: rhdm78-kieserver-cors
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rhdm78-kieserver-cors:latest
    source:
      contextDir: ${DOCKERFILE_CONTEXT}
      git:
        uri: ${DOCKERFILE_REPOSITORY}
        ref: ${DOCKERFILE_REF}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: rhdm-kieserver-rhel8:7.8.0
          namespace: openshift
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: The directory in the git repository containing the Dockerfile.
  name: DOCKERFILE_CONTEXT
  required: true
- description: The git repository containing the Dockerfile
  name: DOCKERFILE_REPOSITORY
  required: true
- description: The ait branchcontaining the Dockerfile
  name: DOCKERFILE_REF
  required: true
  default: master
